### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by jdc20181**
By putting the Script tags at the end the performance/speed/stability increases (Fastest soruce I could find : http://stackoverflow.com/questions/3531314/should-i-write-script-in-the-body-or-the-head-of-the-html I actually learned this quite some time ago and reccomend it for all html files that has any scripts in them)

### CODE REVIEW

**Comment by jdc20181** [comment]
is there a reason it failed?

**Comment by amanuel2** [comment]
Back, no its not failed.. its my dum travis cli..

**Comment by amanuel2** [comment]
Thanks a lot.. it increases performance!

**Comment by jdc20181** [comment]
Yes. It should increase performance.

**Comment by jdc20181** [comment]
one other thing you haven't done is making this more mobile friendly. Without proper tags it will fail google tests when people use it on their site. 

"<meta name="viewport" content="width=device-width, initial-scale=1">" Will do...

**Comment by amanuel2** [comment]
We currently changed a hell ton of stuff... @jdc20181 you should really help us out here if you can :  https://ide.c9.io/amanuel2/ng-fourm#openfile-README.md It will be very helpfull

**Comment by jdc20181** [comment]
- 

'<meta name="viewport" content="width=device-width, initial-scale=1">'

**Comment by jdc20181** [comment]
its not letting me post code :/

**Pull request merged**
